# Generated by Django 4.1.2 on 2022-11-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Size', models.IntegerField(choices=[('1', '10'), ('2', '20'), ('3', '30')])),
                ('Quality', models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('M', 'Medium')], max_length=10)),
            ],
        ),
    ]
