# Generated by Django 4.1.2 on 2022-11-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_productimagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmainmodel',
            name='Size',
            field=models.IntegerField(choices=[('10', '10'), ('20', '20'), ('30', '30')]),
        ),
    ]
