# Generated by Django 4.1.2 on 2022-11-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_productmainmodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmainmodel',
            name='Size',
            field=models.IntegerField(choices=[('10', '1'), ('20', '2'), ('30', '3')]),
        ),
    ]
