# Generated by Django 4.1.2 on 2022-11-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_productmainmodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmainmodel',
            name='Size',
            field=models.IntegerField(choices=[(1, '10'), (2, '20'), (3, '30')]),
        ),
    ]
