# Generated by Django 4.1.2 on 2022-11-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_productmainmodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimagemodel',
            name='PImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
